# Generated by Django 5.2.5 on 2025-09-05 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Books", "Books"),
                    ("Stationery", "Stationery"),
                    ("Rent", "Rent"),
                    ("Subscriptions", "Subscriptions"),
                    ("Shopping", "Shopping"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
