# Generated by Django 5.2.5 on 2025-09-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="tech_stack",
            field=models.CharField(
                choices=[
                    ("MERN Stack", "MERN Stack Development"),
                    ("MEAN Stack", "MEAN Stack Development"),
                    ("AI & Machine Learning", "AI & Machine Learning"),
                    ("Python Development", "Python Development"),
                    ("Data Analytics", "Data Analytics"),
                    ("Cloud Computing", "Cloud Computing"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("DevOps", "DevOps"),
                    ("Blockchain", "Blockchain"),
                    ("Mobile App Development", "Mobile App Development"),
                    ("UI/UX Design", "UI/UX Design"),
                    ("AR/VR Development", "AR/VR Development"),
                    ("Data Science", "Data Science"),
                    ("Game Development", "Game Development"),
                ],
                max_length=50,
            ),
        ),
    ]
