# Generated by Django 5.2.5 on 2025-09-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                ("exercise_minutes", models.IntegerField(blank=True, null=True)),
                ("meals", models.IntegerField(blank=True, null=True)),
                ("hydration_liters", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "😊 Happy"),
                            ("neutral", "😐 Neutral"),
                            ("stressed", "😟 Stressed"),
                            ("anxious", "😰 Anxious"),
                            ("sad", "😢 Sad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stress_level",
                    models.IntegerField(help_text="Rate 1 (low) - 10 (high)"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
