# Generated by Django 5.2.5 on 2025-09-01 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="lectures",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="lectures",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("user", "day", "subject")},
        ),
    ]
