# Generated by Django 5.2.5 on 2025-09-04 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendancelog_lectures_attendancelog_subject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancelog",
            options={"ordering": ["-date", "subject"]},
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="attendance.subject",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="attendance_present",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subject",
            name="attendance_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="attendancelog",
            unique_together={("user", "date", "day", "subject")},
        ),
    ]
