# Generated by Django 5.2.5 on 2025-09-04 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0003_alter_attendancelog_options_alter_attendancelog_day_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="attendance_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subject",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="target_percentage",
            field=models.FloatField(default=75),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
